name: Changes version on release branches

on:
  create:
    branches :
      - 'release/*'

jobs:
  block-release-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Extract tag name
        id: extractTag
        run: |
          echo "TAG_NAME=$(basename $GITHUB_REF_NAME)" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$(basename $GITHUB_REF_NAME)"
      - name: Checkout to main
        uses: actions/checkout@v4
      - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
        with:
          bump-command: mvn versions:set -DnewVersion=${{ steps.extractTag.outputs.TAG_NAME }} -DprocessAllModules
          commit-message: 'Version bump to ${{ steps.extractTag.outputs.TAG_NAME }} from'