name: Block release tags from non-main branches

on:
  create:
    tags:
      - 'release/*'

jobs:
  block-release-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is created from main branch
        run: |
          if [ "${GITHUB_REF_NAME}" != "main" ]; then
            echo "Tags with release/ prefix can only be created from the main branch."
            echo "Current branch: ${GITHUB_REF_NAME}"
            echo "Created tag: ${GITHUB_REF#refs/tags/}"
            exit 1
          fi
      - name: Extract tag name
        id: extractTag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
        with:
          bump-command: mvn versions:set -DnewVersion=${{ steps.extractTag.outputs.TAG_NAME }} -DprocessAllModules
